id: I4CFB79BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:12:29+00:00'
last_modified: '2022-06-07T21:15:19.872200+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20507
  title: ཐོན་མིའི་སློབ་གསོའི་བགྲོ་གླེང་གི་དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས།ཐོན་མིའི་སློབ་གསོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    34C5:
      image_group_id: I8LS20509
      title: ''
      total_pages: 360
      order: 1
      base_file: 34C5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
