id: P004230
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:03:13.124951
source_metadata:
  id: bdr:W8LS20507
  title: ཐོན་མིའི་སློབ་གསོའི་བགྲོ་གླེང་གི་དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས།ཐོན་མིའི་སློབ་གསོ།
  author: ''
  volumes:
    8a993af48fd646f981265db7b04a6809:
      image_group_id: I8LS20509
      title: ''
      volume_number: 1
      total_pages: 360
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
